<a href="https://colab.research.google.com/github/rousharousha/DailyReport/blob/master/Day3(17_06_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
#tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])
#Code:-
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [2]:
#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type
#Code:-
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


In [3]:
#1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
#tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])[ ]
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [4]:
#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type[ ]

import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


In [5]:
#3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]
#Code:-
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [6]:
#4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]
#Code:-
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [7]:
#5.Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [8]:
#6.Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
#Code:-
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [9]:
#7.Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
#Code:-
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


In [10]:
#8.Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5
#Code:-
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [11]:
#9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000
#Code:-
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


In [12]:
#10.Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}
#Code:-
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [25]:
#11.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable
#Code:-
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x)

Original Array:
[[0.57896089 0.02578481 0.35956408 0.01313979]
 [0.99411167 0.52035298 0.64376089 0.4868204 ]
 [0.11116108 0.40340217 0.54968082 0.82454403]
 [0.30675936 0.19629001 0.80807841 0.5943139 ]]


In [24]:
#12.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.
#Code:-
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.45433577 0.2580506  0.42753965 0.98120255 0.30906696 0.31118265
  0.18531258 0.48801143 0.19739271 0.65704291]
 [0.73677947 0.52426051 0.17018644 0.91029862 0.45576036 0.94915803
  0.17592983 0.8276385  0.01147135 0.49408806]
 [0.64204829 0.28285665 0.3329348  0.32977997 0.22717403 0.14617743
  0.61078119 0.216422   0.53315308 0.86542678]
 [0.72851208 0.81405201 0.4083909  0.41329779 0.72865239 0.27119215
  0.44289117 0.37396927 0.48335539 0.41149126]
 [0.44999305 0.10327658 0.52292787 0.18803481 0.4658976  0.56460915
  0.96865022 0.28769066 0.18349736 0.03009933]
 [0.79267003 0.45077018 0.59029067 0.92512475 0.63545257 0.10829421
  0.73713133 0.69189874 0.02741555 0.61219173]
 [0.35683622 0.13919039 0.39256651 0.33473293 0.94838833 0.96835428
  0.29874065 0.38023028 0.3871583  0.0459906 ]
 [0.2873179  0.54115666 0.59535866 0.15729277 0.77396391 0.18487232
  0.64274472 0.31854211 0.41258189 0.93346215]
 [0.06870585 0.10149921 0.50430966 0.7829852  0.67611296 0.59411

In [23]:
#13.Write a NumPy program to generate 8 random integers between 100 and 300
#Code:-
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)


[178 115 200 117 231 158 204 179]


In [22]:
#14.Write a NumPy program to create a random integer nos of size 20 and sort it
#Code:-
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.30914804 0.05467441 0.7623193  0.52612471 0.48263179 0.0795539
 0.98095046 0.31791564 0.45857165 0.17372571 0.95115478 0.21124256
 0.35177889 0.04063353 0.14422563 0.76596377 0.95188371 0.7054014
 0.83070625 0.41812205]
Sorted array:
[0.04063353 0.05467441 0.0795539  0.14422563 0.17372571 0.21124256
 0.30914804 0.31791564 0.35177889 0.41812205 0.45857165 0.48263179
 0.52612471 0.7054014  0.7623193  0.76596377 0.83070625 0.95115478
 0.95188371 0.98095046]
